from google.appengine.ext import db

class User(db.Model):
    username      = db.StringProperty(required = True)
    password_hash = db.StringProperty(required = True)
    email         = db.StringProperty(required = True)
    activated     = db.StringProperty(required = True)
    activation_key= db.StringProperty(required = True)

class ThinDB(db.Model):
    username      = db.StringProperty(required = True)
    asset         = db.StringProperty(required = True)
    asset_key     = db.StringProperty(required = True)
    str_value     = db.StringProperty(required = False)
    int_value     = db.IntegerProperty(required= False)

class Member(db.Model):
    first_name    = db.StringProperty(required = True)
    last_name     = db.StringProperty(required = True)
    email         = db.EmailProperty(required = True)
    headline      = db.TextProperty(required = True)
    active        = db.BooleanProperty(required = True)
    country       = db.StringProperty(required = False)
    city          = db.StringProperty(required = False)
    state         = db.StringProperty(required = False)
    zip_code      = db.StringProperty(required = False)
    linkedin      = db.LinkProperty(required = False)
    facebook      = db.LinkProperty(required = False)
    twitter       = db.StringProperty(required = False)
    skype         = db.StringProperty(required = False)
    blog          = db.LinkProperty(required = False)
    phone         = db.PhoneNumberProperty(required = False)
    username      = db.UserProperty(required = True)
    created_at    = db.DateTimeProperty(auto_now_add = True)
    updated_at    = db.DateTimeProperty(auto_now = True)

class Requestor(db.Model):
    email         =db.EmailProperty(required = True)
    first_name    =db.StringProperty(required = True)
    last_name     =db.StringProperty(required = True)
    country       =db.StringProperty(required = True)
    education     =db.StringProperty(required = False)
    facebook      =db.LinkProperty(required = False)
    linkedin      =db.LinkProperty(required = False)
    twitter       =db.StringProperty(required = False)
    skype         =db.StringProperty(required = False)
    blog          = db.LinkProperty(required = False)
    expertise_sought_name_1     =db.StringProperty(required = True)
    expertise_sought_name_2     =db.StringProperty(required = True)
    expertise_sought_name_3     =db.StringProperty(required = True)
    expertise_name_1            =db.StringProperty(required = True)
    expertise_name_2            =db.StringProperty(required = True)
    expertise_name_3            =db.StringProperty(required = True)
    expertise_name_4            =db.StringProperty(required = False)
    expertise_name_5            =db.StringProperty(required = False)
    expertise_level_1           =db.StringProperty(required = True)
    expertise_level_2           =db.StringProperty(required = True)
    expertise_level_3           =db.StringProperty(required = True)
    expertise_level_4           =db.StringProperty(required = False)
    expertise_level_5           =db.StringProperty(required = False)
    reason_for_learning         =db.TextProperty(required = False)
    how_they_heard_of_us        =db.TextProperty(required = False)
    learning_style              =db.TextProperty(required = False)
    profession                  =db.TextProperty(required = False)
    current_method              =db.TextProperty(required = True)
    remote_project              =db.TextProperty(required = False)
    created_at    =db.DateTimeProperty(required = True,auto_now_add = True)
    updated_at    =db.DateTimeProperty(required = True,auto_now = True)
